Feature/motor
jadjer/electronic-throttle-control-unit-esp32 pull request #11
Opened 2023-09-30 17:58 UTC by jadjer

2023-09-30 18:55 UTC, IllidanSR requested changes

2023-09-30 18:55 UTC, IllidanSR commented on components/motor/src/Motor.cpp
> +        return 1000000 / _currentStepPeriod_InUS;
10^6 - миллисекунды?

2023-09-30 18:55 UTC, IllidanSR commented on components/motor/src/Motor.cpp
> +    {
Не нужно

2023-09-30 18:55 UTC, IllidanSR commented on components/motor/src/Motor.cpp
> +    uint64_t currentTime_InUS = esp_timer_get_time();
const

2023-09-30 18:55 UTC, IllidanSR commented on components/motor/src/Motor.cpp
> +    uint64_t periodSinceLastStep_InUS = currentTime_InUS - _lastStepTime_InUS;
const

2023-09-30 18:55 UTC, IllidanSR commented on components/motor/src/Motor.cpp
> +}
```cpp
uint32_t Motor::determinePeriodOfNextStep()
{
    uint32_t distanceToTarget_Unsigned = abs(_targetPosition_InSteps - _currentPosition_InSteps);
    auto currentStepPeriodSquared = _currentStepPeriod_InUS * _currentStepPeriod_InUS;
    auto decelerationDistance_InSteps = calcDecelerationDistanceInSteps();

    if (_directionOfMotion == 1) {
        if ((distanceToTarget_Unsigned < decelerationDistance_InSteps || _nextStepPeriod_InUS < _desiredPeriod_InUSPerStep) && _currentStepPeriod_InUS >= _periodOfSlowestStep_InUS) {
            _directionOfMotion = -1;
            m_driver->setDirection(motor::driver::MOTOR_ROTATE_OTHERWISE);
        }
    } else if (_directionOfMotion == -1) {
        if ((distanceToTarget_Unsigned < decelerationDistance_InSteps || _nextStepPeriod_InUS < _desiredPeriod_InUSPerStep) && _currentStepPeriod_InUS >= _periodOfSlowestStep_InUS) {
            _directionOfMotion = 1;
            m_driver->setDirection(motor::driver::MOTOR_ROTATE_CLOCKWISE);
        }
    }

    double stepPeriodChangeFactor = (_directionOfMotion == 1) ? -_acceleration_InStepsPerUSPerUS : _deceleration_InStepsPerUSPerUS;
    
    _nextStepPeriod_InUS = _currentStepPeriod_InUS + _currentStepPeriod_InUS * stepPeriodChangeFactor * currentStepPeriodSquared;

    if (_nextStepPeriod_InUS < _desiredPeriod_InUSPerStep) {
        _nextStepPeriod_InUS = _desiredPeriod_InUSPerStep;
    } else if (_nextStepPeriod_InUS > _periodOfSlowestStep_InUS) {
        _nextStepPeriod_InUS = _periodOfSlowestStep_InUS;
    }

    return _nextStepPeriod_InUS;
}
```

2023-09-30 18:55 UTC, IllidanSR commented on main/Drv8825.hpp
> +    std::unique_ptr<gpio::interface::IPin> m_directionPin;
мб в pimpl вынести?

2023-10-01 12:52 UTC, jadjer commented on components/motor/src/Motor.cpp
> +        return 1000000 / _currentStepPeriod_InUS;
10^6 - микросекунды.

Чтоб перевести из микросекунд в секунды, нужно значение в микросекундах разделить на 1^6.
Ну а здесь период

2024-03-21 09:06 UTC, merged