feat: Refactored code
jadjer/electronic-throttle-control-unit-esp32 pull request #3
Opened 2023-08-30 13:18 UTC by jadjer

2023-08-30 16:05 UTC, IllidanSR requested changes

2023-08-30 16:05 UTC, IllidanSR commented on components/common/src/Exception.cpp
> +ErrorCode::Enum Exception::code() const noexcept
Это принятый код стайл?

2023-08-30 16:05 UTC, IllidanSR commented on components/ecu/include/ECU/Interface/NetworkConnector.hpp
> +namespace Interface
Кажется, это излишне - файл и так находится в директории Interface

2023-08-30 16:05 UTC, IllidanSR commented on components/ecu/include/ECU/KLineNetworkConnector.hpp
> +#include <chrono>
Не ипользуется

2023-08-30 16:05 UTC, IllidanSR commented on components/ecu/include/ECU/UartNetworkConnector.hpp
> +    std::mutex m_mutex;
инклюд для мьютекса

2023-08-30 16:05 UTC, IllidanSR commented on components/ecu/src/HondaECU.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(200));
Насколько я помню, эти задержки определены доками, давай их предефайним может быть в текущем .cpp файле как глобальные переменные, ну или в конструкторе как константы, кажется, что они не будут меняться и мы можем их описать как дефолтные

2023-08-30 16:05 UTC, IllidanSR commented on components/ecu/src/KLineNetworkConnector.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(120));
Тоже самое, по-моему эти делеи из документации

2023-08-30 16:05 UTC, IllidanSR commented on components/ecu/src/KLineNetworkConnector.cpp
> +        return;
Может быть бросим исключение о том, что есть проблемы с коннектом?

2023-08-30 16:05 UTC, IllidanSR commented on components/ecu/src/KLineNetworkConnector.cpp
> +    Bytes payload = m_networkConnectorPtr->readBytes(dataLength - minimalDataLength);
const?

2023-08-30 16:05 UTC, IllidanSR commented on components/ecu/src/UartNetworkConnector.cpp
> +    auto delay_InUS = (bytes / bytesPerMillisecond) + minimalDelay_InUS;
если это микросекунды - тогда лучше microseconds, греческая мю для нашей раскладки не доступна вроде =)

2023-08-30 16:05 UTC, IllidanSR commented on components/executor/src/Executor.cpp
> +    m_nodes.clear();
Не нужно, деструктор поклинит всё

2023-08-30 16:05 UTC, IllidanSR commented on components/executor/src/Executor.cpp
> +    while (m_enable)
А точно хорошая идея без задержки здесь быть? мб какой Делей в 10 мкс поставить хотя бы для цикла опроса?

2023-08-30 16:23 UTC, jadjer commented on components/ecu/include/ECU/Interface/NetworkConnector.hpp
> +namespace Interface
Задумка чтоб структура namespace соответствовала дереву каталогов

2023-08-30 16:35 UTC, jadjer commented on components/ecu/src/UartNetworkConnector.cpp
> +    auto delay_InUS = (bytes / bytesPerMillisecond) + minimalDelay_InUS;
Допускается украшение до US когда мю не доступна

2023-08-30 17:19 UTC, jadjer commented on components/executor/src/Executor.cpp
> +    m_nodes.clear();
Это старый код, я только поменял структуру компонента

2023-08-30 17:21 UTC, jadjer commented on components/executor/src/Executor.cpp
> +    while (m_enable)
10 мкс задержки очень много. К Executor у меня ещё много вопросов

2023-09-02 07:58 UTC, IllidanSR commented on components/ecu/include/ECU/Interface/NetworkConnector.hpp
> +namespace Interface
Кажется немного избыточно, но окей, если так задумано

2023-09-02 07:59 UTC, IllidanSR commented on components/ecu/src/UartNetworkConnector.cpp
> +    auto delay_InUS = (bytes / bytesPerMillisecond) + minimalDelay_InUS;
О_о, не знал, если честно. Окей =)

2023-09-02 08:00 UTC, IllidanSR approved these changes

2023-09-02 08:30 UTC, merged